#!/bin/sh
# live-build auto/config — called by lb config
set -e
lb config noauto \
    --architecture amd64 \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends false \
    "${@}"
